%YAML 1.2
---
blog:
  - url: 'http://middlewareblog.redhat.com/2017/07/27/swaggeropenapi-for-enterprise-java-microservices/'
    title: 'Swagger/OpenAPI for Enterprise Java microservices'
    date: '2017-07-27'
    author: 'Cesar Saavedra'
    tags:
      - community
      - microservices
    extract: >
      On June 13, 2017, SmartBear joined the Eclipse
      MicroProfile project, an open source community specification for Enterprise Java microservices. As someone
      interested in microservices, why is this news important?

  - url: 'https://mikecroft.io/2017/07/11/microprofile-1-year-on.html'
    title: 'The MicroProfile Turns One'
    date: '2017-07-11'
    author: mikecroft
    image: 'http://mikecroft.io/assets/mp-announcement.jpg'
    tags:
      - microprofile
    extract: >
      As I write this blog post, on Tuesday 27th June 2017, I’m looking through memories of where I was on this day
      in 2016: participating in the keynote speech at Red Hat’s DevNation conference in San Francisco.

  - url: 'http://sdtimes.com/eclipse-microprofile-optimizes-java-ee/'
    title: 'Industry Spotlight: Eclipse MicroProfile optimizes Java EE'
    date: '2017-05-31'
    author: 'Lisa Morgan'
    tags:
      - news
    extract: >
      From [Lisa Morgan] Java EE developers are now experimenting with microservices and they need a coherent way to
      optimize their development efforts. Over the years, Java EE has supported distributed application architectures
      based on RMI/IIOP, Web Services and REST. The Eclipse MicroProfile project is the next step in that evolution
      because it optimizes enterprise Java for a microservices architecture.

  - url: 'https://developers.redhat.com/video/youtube/YGC2b8k2nfg/'
    title: 'MicroProfile: Optimizing Java EE for a microservices architecture'
    date: '2016-05-15'
    author: 'developers.redhat.com'
    tags:
      - microprofile
      - video
    extract: >
      Hear from John Clingan, Sr. Principal Product Manager, Red Hat, and Ken Finnigan,
      Red Hat in this breakout session at Red Hat Summit 2017. MicroProfile is a community-led effort to bring
      microservices to Java Platform, Enterprise Edition (Java EE) across multiple implementations, including WildFly
      Swarm, IBM WebSphere Application Server Liberty Profile, Apache TomEE, Payara Micro, and Hammock.

  - url: 'http://middlewareblog.redhat.com/2017/05/02/eclipse-microprofile-continues-its-growth-in-the-market/'
    title: 'Eclipse MicroProfile continues its growth in the market'
    date: '2017-05-02'
    author: 'Cesar Saavedra'
    tags:
      - news
    extract: >
      Organizations that have already embarked or are thinking about starting a digital transformation journey are
      assessing and looking for ways to leverage their Java EE expertise. IT development and operations have built
      Java expertise over years, and there is a challenge to balance their existing skill base with new digitally
      transformative technologies, such as microservices, APIs, container-based architectures, and reactive programming.
      Eclipse MicroProfile is an open source project and one of those digitally transformative technologies that
      enables and optimizes the development of microservices — using familiar Java EE technologies and APIs.
